@startuml

title Joueur

class Joueur {
    - nom : String
    - vie : int
    - mana : int
    - xp : int
    - collision : boolean
    - positionX : int 
    - positionY : int
    + Joueur(String,int,int)
    + move(int,int) : void
    + changerVie(int) : void
    + changerMana(int) : void
    + changerXp(int) : void
    + getVie() : int
    + getMana() : int
    + getXp() : int
    + getPositionX() : int
    + getPositionY() : int 
    + getCollision() : boolean
    + setPositionX(int) : void
    + setPositionY(int) : void
    + getNom() : String
    + bloquer() : void
    + toString() : String
}

@enduml